apiVersion: v1
kind: Service
metadata:
  name: flightrobustness-service
  namespace: ${K8S_NAMESPACE:-poc}
  labels:
    app: flightrobustness
spec:
  selector:
    app: flightrobustness
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
