apiVersion: v1
kind: Secret
metadata:
  name: flightrobustness-secrets
  namespace: ${K8S_NAMESPACE:-poc}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
  AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
